services:
  meow-printer:
    build: .
    image: scientistpun/meow-printer:2.4.3
    container_name: meow-printer
    ports:
      - "3000:3000"
    environment:
      - CUPS_HOST=192.168.10.1
      - CUPS_PORT=631
      - CUPS_USER=admin
      - CUPS_PWD=123456
      - DEV=false
      - TZ=Asia/Shanghai
    volumes:
      - ./public:/app/public
      - ./logs:/app/logs
    restart: unless-stopped
    network_mode: host
