services:
  meow-printer:
    build:
      context: .
      platform: 
        - linux/amd64
        - linux/arm64
    container_name: meow-printer
    ports:
      - "3000:3000"
    environment:
      - CUPS_HOST=192.168.10.1
      - CUPS_PORT=631
    volumes:
      - /var/run/cups.sock:/var/run/cups.sock:ro
      - ./public/cache:/app/public/cache
      - ./public/uploads:/app/public/uploads
      - ./public/fonts:/app/public/fonts
      - ./logs:/app/logs
    restart: unless-stopped
    network_mode: host
